### ISSUE TITLE
mock/index.js syntax error

### ISSUE THREAD

**Issue by Roamin** [ct-adc/webpack#2]
## What happned

In Express 4.x, the way to get the route parameters object is:

```
req.params
```

not:

```
req.body
```

## Screenshot

![error](https://cloud.githubusercontent.com/assets/11537595/26307434/150d2690-3f27-11e7-8fd3-dbf53383dcae.png)

See more  details by clicking [http://www.expressjs.com.cn/4x/api.html#req.params](http://www.expressjs.com.cn/4x/api.html#req.params)

**Comment by rubyisapm** [comment]
add body-parser
